# Generated by Django 5.0.6 on 2024-06-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='bydefault@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
